### PR TITLE
Compatibility with NextJS and SSR

### PR DESCRIPTION
**Pull request by 42shadow42**

### CODE REVIEW

**Comment by 42shadow42** [comment]
Hmm, I had it working at some point, I must have some last minute changes that broke that piece. 

As for using rollup and webpack, I've read somewhere that rollup is better for libraries, and webpack for applications, so since the component is a library I used that. It wasn't worth making the dev server work with rollup to me.

I'll look into what I broke that made the typing not work there.

**Comment by 42shadow42** [comment]
I figured out the problem but I'm not sure how to fix it atm, when running npm run dev, it generates a file index.module.css.d.ts, but that file interferes with the rollup build.

Also to answer your comment about typescript compilation the compilation to the bundle compiles the bundle from typescript to js. The tsc call generates the typings so typescript can be used, it shouldn't be generating a bundle because we told it to emit declarations only. There is a newer version of the typescript plugin for rollup that generates the typings natively, but it currently isn't compatible with the css inlining plugin. So we have to use the workaround for now.

**Comment by CeamKrier** [comment]
> I figured out the problem but I'm not sure how to fix it atm, when running npm run dev, it generates a file index.module.css.d.ts, but that file interferes with the rollup build.
> 
> Also to answer your comment about typescript compilation the compilation to the bundle compiles the bundle from typescript to js. The tsc call generates the typings so typescript can be used, it shouldn't be generating a bundle because we told it to emit declarations only. There is a newer version of the typescript plugin for rollup that generates the typings natively, but it currently isn't compatible with the css inlining plugin. So we have to use the workaround for now.

Yes, my bad. I misinterpreted the command, sorry. I have a working version on `no-css` branch. I tested it with a next.js starter app and it worked. What I did was, ripping off the css implementation and going with inline styles and a bit of the styled-components for using pseudo-class features. With that, I won't be able to merge your PR because it's based on a separate bundler which I believe would affect the long term sustainability of the library if I accept it. I hope you understand.

Also, it would be great if you can also check it with your next app for verification. After that, I'll merge the branch to the master.

**Comment by 42shadow42** [comment]
It is functional on your branch but the look and feel changed for the worse see below, the top is the original version, the bottom is with the styled components changes.

image

**Comment by 42shadow42** [comment]
I get this warning which may be related to the styling issue I'm seeing, do you get this too? index.js:1 Warning: Prop `className` did not match. Server: "sc-fzozJi bflZyX" Client: "sc-AxirZ iUqniJ"
    in input (created by styled.input)
    in styled.input (created by Editable)
    in div (created by styled.div)
    in styled.div (created by Editable)
    in Editable (created by Page)
    in div (created by Jumbotron)
    in Jumbotron (created by Page)
    in Page (at _app.tsx:39)
    in MyApp
    in Container (created by AppContainer)
    in AppContainer

**Comment by 42shadow42** [comment]
It's your call to make, but you may want to consider using rollup for your library, as suggested somewhat by the following articles about the subject.

https://medium.com/jsdownunder/rollup-vs-webpack-javascript-bundling-in-2018-b35758a2268
https://medium.com/better-programming/the-battle-of-bundlers-6333a4e3eda9

I think doing so gives some advantages over the style components solution. It allows you to use native css for one thing, and even potentially sass if your styles ever become that complex.

One disadvantage of both solutions though is theming I don't think either of them allow for easy theming like libraries like bootstrap provide. If you desire theming in your component which I think would be a desirable feature you may consider using sass instead of css, prefixing your styles appropriately for the the component library, and having consumers import the sass/css into their application.

**Comment by CeamKrier** [comment]
> It is functional on your branch but the look and feel changed for the worse see below, the top is the original version, the bottom is with the styled components changes.
> 
> image

I might have distorted the stylings a little bit while transforming them. But you can always set your own stylings via exposed props of [the library](https://github.com/CeamKrier/react-editable-title#api)



> I get this warning which may be related to the styling issue I'm seeing, do you get this too? index.js:1 Warning: Prop `className` did not match. Server: "sc-fzozJi bflZyX" Client: "sc-AxirZ iUqniJ"
> in input (created by styled.input)
> in styled.input (created by Editable)
> in div (created by styled.div)
> in styled.div (created by Editable)
> in Editable (created by Page)
> in div (created by Jumbotron)
> in Jumbotron (created by Page)
> in Page (at _app.tsx:39)
> in MyApp
> in Container (created by AppContainer)
> in AppContainer

I haven't extensively tested it on the next.js but haven't noticed such an error.



> It's your call to make, but you may want to consider using rollup for your library, as suggested somewhat by the following articles about the subject.
> 
> https://medium.com/jsdownunder/rollup-vs-webpack-javascript-bundling-in-2018-b35758a2268
> https://medium.com/better-programming/the-battle-of-bundlers-6333a4e3eda9
> 
> I think doing so gives some advantages over the style components solution. It allows you to use native css for one thing, and even potentially sass if your styles ever become that complex.
> 
> One disadvantage of both solutions though is theming I don't think either of them allow for easy theming like libraries like bootstrap provide. If you desire theming in your component which I think would be a desirable feature you may consider using sass instead of css, prefixing your styles appropriately for the the component library, and having consumers import the sass/css into their application.

Yes, I am thinking to port the bundler to rollup. I'll probably use the implementation you posted on PR as the base for it. But before, I need to check its documentation for a bit.

Then, I'm gonna merge the `no-css` branch to master so you can start using it. I'll close the PR and issue after shifting to rollup.

**Comment by 42shadow42** [comment]
If you don't mind me asking, how did you import no-css into your next project, I've had to try a number of ways even to get it working with the UI off and that error, maybe if I had the steps you used to install it I could get it working properly from the branch.

**Comment by CeamKrier** [comment]
> If you don't mind me asking, how did you import no-css into your next project, I've had to try a number of ways even to get it working with the UI off and that error, maybe if I had the steps you used to install it I could get it working properly from the branch.

Initially, I tried to link the local version of the `no-css` branch via `npm link` but it did not work. Then I followed an intuitive way to make it work.

- I added the old version of the library from npm registry via `npm i react-editable-title`
- Opened the installed library folder inside the `node_modules` and replaced content of the `lib` folder with `no-css` branch's `lib` folder content.
- Lastly, I have installed `styled-components` and `react-icons` to next.js project. Because new bundle depending on those libraries too.

image

**Comment by CeamKrier** [comment]
And about the rollup, I would love to use it as a total replacement of the webpack. But as far as what I have googled, I could not find a solid substitute to `webpack-dev-server`. 

If you have time, can you help me with it? I'm posting what I have got so far with the configuration file of the rollup.

```
import typescript from '@rollup/plugin-typescript'
import livereload from 'rollup-plugin-livereload'
import serve from 'rollup-plugin-serve'

const isDev = process.env.DEV === 'true'
const dir = isDev ? 'src/dev/' : 'lib'
const input = isDev ? 'src/dev/showcase.tsx' : 'src/index.tsx'

export default {
    input: input,
    output: {
        format: 'cjs',
        dir: dir,
        sourcemap: true
    },
    external: [
        'react'
    ],
    plugins: [
      typescript({
        sourceMap: true
      }),
      isDev && livereload(),
      isDev && serve({
        open: true,
        contentBase: 'src/dev/',
        port: 2000,
      })
    ]
}; 
```

package.json 
image

**Comment by CeamKrier** [comment]
> > If you don't mind me asking, how did you import no-css into your next project, I've had to try a number of ways even to get it working with the UI off and that error, maybe if I had the steps you used to install it I could get it working properly from the branch.
> 
> Initially, I tried to link the local version of the `no-css` branch via `npm link` but it did not work. Then I followed an intuitive way to make it work.
> 
> * I added the old version of the library from npm registry via `npm i react-editable-title`
> * Opened the installed library folder inside the `node_modules` and replaced content of the `lib` folder with `no-css` branch's `lib` folder content.
> * Lastly, I have installed `styled-components` and `react-icons` to next.js project. Because new bundle depending on those libraries too.
> 
> image

I published the updated version so you don't need to follow the steps that I specified above. Just pull the updated version of the library from the npm registry.

**Comment by 42shadow42** [comment]
That looks right in your example. Mine still doesn't look quite right though. Possibly something on my end.

As for the rollup server, I don't think you are going to find a good one, I think that's one of the reasons why webpack is better for applications is the webpack-dev-server. Speaking of the webpack-dev-server. I pulled down the latest version of your no-css branch and the dev server isn't working for me. Does it work for you?

**Comment by 42shadow42** [comment]
> That looks right in your example. Mine still doesn't look quite right though. Possibly something on my end.

Looks like bootstrap is conflicting with it, I didn't get that on this branch, could be related to the styles cleanup you did.

**Comment by CeamKrier** [comment]
> > That looks right in your example. Mine still doesn't look quite right though. Possibly something on my end.
> 
> Looks like bootstrap is conflicting with it, I didn't get that on this branch, could be related to the styles cleanup you did.

Instead of trying locally, use the latest version on the npm registry. Dunno what kind of conflict you facing with but as a general suggestion, remove `node_modules` and `.next` folder and do a clean install and build. Let's see how that will do.

**Comment by 42shadow42** [comment]
> Instead of trying locally, use the latest version on the npm registry. Dunno what kind of conflict you facing with but as a general suggestion, remove `node_modules` and `.next` folder and do a clean install and build. Let's see how that will do.

I did try locally, and that's what worked perfectly without bootstrap, I copied your new style over to my branch and they both have the same problem when bootstrap is present. Something you removed was protecting it from interference though because it looked alright before the refactored styles.

**Comment by 42shadow42** [comment]
Would it be too much to ask that you add line-height: 1em; back onto the buttons? I think I've identified that as the culprit of this visual issue with bootstrap. The top is with the line-height the bottom is without.

image

**Pull request closed without merging**
